#!/bin/bash

if ! [ -f out/zjuthesis.fls ]; then
    echo "Cannot find file 'out/zjuthesis.fls', which is generated by latexmk"
    echo "Please use 'latexmk' command to compile zjuthesis first, then run"
    echo "this script under the project root dir to count words"
    exit 1
fi

cat out/zjuthesis.fls                 \
    | uniq                            \
    | grep body                       \
    | grep .tex                       \
    | grep -v thanksto.tex            \
    | grep -v acknowledgement.tex     \
    | grep -v review.tex              \
    | grep -v original.tex            \
    | grep -v cv.tex                  \
    | cut -d ' ' -f 2                 \
    | awk '{ print "\\input{"$1"}" }' \
    > out/zjuthesis.wordcnt           \
;

for candidate in \
    texcount \
    texcount.pl \
    /mnt/d/TexLive/*/bin/windows/texcount.exe \
    /mnt/d/texlive/*/bin/windows/texcount.exe \
    /mnt/c/TexLive/*/bin/windows/texcount.exe \
    /mnt/c/texlive/*/bin/windows/texcount.exe \
    /d/TexLive/*/bin/windows/texcount.exe \
    /d/texlive/*/bin/windows/texcount.exe \
    /c/TexLive/*/bin/windows/texcount.exe \
    /c/texlive/*/bin/windows/texcount.exe
do
    if command -v "$candidate" >/dev/null 2>&1 || [ -f "$candidate" ]; then
        "$candidate" out/zjuthesis.wordcnt -inc
        exit 0
    fi
done

echo "Cannot find 'texcount' or 'texcount.pl' in PATH."
echo "Please install TeX Live/MiKTeX and ensure texcount is available in PATH."
echo "You may also add TeX Live bin path, e.g. D:\\TexLive\\2023\\bin\\windows."
exit 1
